name: NPM Auto Deprecate

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  auto-deprecate:
    name: NPM Auto Deprecate
    runs-on: ubuntu-latest
    if: github.repository_owner = "maclary"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setep PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Deprecate versions
        run: pnpm npm-deprecate
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
