name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: The number of the PR that is being deployed.
        required: true
  push:
    branches:
      - main

jobs:
  linting:
    uses: ./.github/workflows/continuous-integration.yml
  
  building:
    uses: ./.github/workflows/continuous-integration.yml

  publish:
    name: Publish Next to NPM
    needs: [linting, building]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'maclary'
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setep PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: echo '::add-matcher::.github/problemMatchers/tsc.json'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - id: determine-tag
        run: |
          # Push, next
          if [[ ${{ github.event_name }} == 'push' ]]
          then
            echo '::set-output name=tag::next'

          # Dispatch, pull request
          elif [[ ${{ github.event.inputs.pull_request != '' }} ]]
          then
            NUMBER=${{ github.event.inputs.pull_request }}
            echo "::set-output name=tag::pr-${NUMBER}"
          fi

      - name: Public package
        if: steps.determine-tag.outputs.tag != ''
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

          TAG=${{ steps.determine-tag.outputs.tag }}
          VERSION="${TAG}.$(git rev-parse --verify --short HEAD)"

          pnpm release --preid ${VERSION}
          pnpm publish --tag ${TAG} --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
