name: NPM Deprecate PR Versions On Merge

on:
  pull_request:
    types:
      - closed

jobs:
  deprecate-on-merge:
    name: NPM Deprecate PR Versions On Merge
    runs-on: ubuntu-latest
    if: github.repository_owner = 'maclary'
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setep PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Deprecate version
        run: pnpm npm-deprecate --name '*pr-${{ github.event.number }}' --package 'maclary'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
