name: Generate Documentation

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    name: Generate Documentaion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - name: Build documentation
        run: npm run clean && npm run docs

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: maclary.js.org